language: go

services:
  - docker

go:
  - "1.18.6"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libsystemd-dev

script: make build build-test test functional-test-redis functional-test-sla
